# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20150721_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=128, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Wiadomo\u015b\u0107')),
                ('d_created', models.DateTimeField(auto_now=True, verbose_name='Odebrano')),
            ],
        ),
        migrations.AlterField(
            model_name='cimage',
            name='image',
            field=models.ImageField(upload_to=b'pics/', verbose_name='Plik zdj\u0119cia'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='etap',
            field=models.CharField(blank=True, choices=[(b'etap1', 'Prace ziemne i fundamenty.'), (b'etap2', 'Wykonanie gabaryt\xf3w domu'), (b'etap3', 'Instalacje'), (b'etap4', 'Wyko\u0144czenie wn\u0119trza'), (b'etap5', 'Wyko\u0144czenie zewn\u0105trz'), (b'etap6', 'Osiedle i okolice')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to=b'pics/', verbose_name='Plik zdj\u0119cia'),
        ),
        migrations.AlterField(
            model_name='housetype',
            name='short_desc',
            field=models.TextField(verbose_name='Kr\xf3tki opis'),
        ),
        migrations.AlterField(
            model_name='housetype',
            name='space',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Metra\u017c'),
        ),
    ]
